export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_LOADED = 'PRODUCT_LIST_LOADED';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';


export const PRODUCT_DETAILS_LOADED = 'PRODUCT_DETAILS_LOADED';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_LOADING = 'PRODUCT_DETAILS_LOADING';

